### ISSUE TITLE
Tool utilization issues

### ISSUE THREAD

**Issue by value-0** [AnkioTomas/unveilr#7]
This tool doesn't seem to support the decompilation of WeChat packages within the Android emulator, what should I do?

**Comment by AnkioTomas** [comment]
1. 你应该从微信的数据目录提取微信小程序的包（*.wxpkg）
2. 然后在PC运行命令获得反编译的小程序源码

**Comment by aijiaxiaoxue** [comment]
uniapp 编译的小程序代码，反编译后 报错严重

**Comment by AnkioTomas** [comment]
> uniapp 编译的小程序代码，反编译后 报错严重

反编译 不等于 百分百还原源代码。
